### ISSUE TITLE
Bug: 30 Day Rolling Summary Graph Looks Odd

### ISSUE THREAD

**Issue by sgalizia** [andythorne/magurokun-issues#18]
In the summary for an item that only has a single day that it was sold, the bar graph for the dates looks a bit odd. It seems to stretch across multiple days?

![image](https://user-images.githubusercontent.com/1574010/80235789-0b462800-860f-11ea-9b37-96ab85825915.png)

Maybe this is intended and the dates along the bottom are incorrect?

**Comment by sgalizia** [comment]
I also just realized all those dates are in the future o.O, including the sale date in the daily summary being incorrect. The only correct date is in the Heatmap

**Comment by sgalizia** [comment]
One more example with more sales but the dates are definitely incorrect. I guess I am going to sell one of these this Sunday? 😆 
![image](https://user-images.githubusercontent.com/1574010/80236242-b7880e80-860f-11ea-8605-832db5912b69.png)

**Comment by andythorne** [comment]
Can I claim that's some new next-gen AI prediction? 😂

Tbh I've seen this bug once before but I thought I had fixed it, it seems not! The problem is with timezones... all the dates stored are in the UTC, but anyone not in a UTC zone (including me) sees slightly offset data. I'll see if I can get a fix tonight for this, as it looks terrible!

Thanks for the report again 🙌!

**Comment by andythorne** [comment]
Should be fixed now! Thanks!

**Comment by sgalizia** [comment]
I am still seeing data for sales in the future. I refreshed the page and navigated around and back to this query and I still see issues with this sale

![image](https://user-images.githubusercontent.com/1574010/80246844-f2933d80-8621-11ea-8a7e-86a9b0ac12ea.png)
